// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package db

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (
  user_id, provider, provider_user_id, created_at, updated_at
) VALUES (
  $1, $2, $3, NOW(), NOW()
)
RETURNING id, user_id, provider, provider_user_id, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM identities WHERE id = $1
`

func (q *Queries) DeleteIdentity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIdentity, id)
	return err
}

const getIdentityByProviderAndUserID = `-- name: GetIdentityByProviderAndUserID :one
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM identities
WHERE provider = $1 AND provider_user_id = $2
LIMIT 1
`

type GetIdentityByProviderAndUserIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetIdentityByProviderAndUserID(ctx context.Context, arg GetIdentityByProviderAndUserIDParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProviderAndUserID, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM identities
WHERE user_id = $1
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID int64) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
