// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_nonces.sql

package db

import (
	"context"
	"time"
)

const deleteLoginNonce = `-- name: DeleteLoginNonce :exec
DELETE FROM login_nonces
WHERE address = $1
`

func (q *Queries) DeleteLoginNonce(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginNonce, address)
	return err
}

const getLoginNonce = `-- name: GetLoginNonce :one
SELECT address, nonce, expires_at, message, created_at
FROM login_nonces
WHERE address = $1
LIMIT 1
`

type GetLoginNonceRow struct {
	Address   string    `json:"address"`
	Nonce     string    `json:"nonce"`
	ExpiresAt time.Time `json:"expires_at"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetLoginNonce(ctx context.Context, address string) (GetLoginNonceRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginNonce, address)
	var i GetLoginNonceRow
	err := row.Scan(
		&i.Address,
		&i.Nonce,
		&i.ExpiresAt,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const upsertLoginNonce = `-- name: UpsertLoginNonce :exec
INSERT INTO login_nonces (address, nonce, expires_at, message, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (address) DO UPDATE
SET nonce = EXCLUDED.nonce,
    expires_at = EXCLUDED.expires_at,
    message = EXCLUDED.message
`

type UpsertLoginNonceParams struct {
	Address   string    `json:"address"`
	Nonce     string    `json:"nonce"`
	ExpiresAt time.Time `json:"expires_at"`
	Message   string    `json:"message"`
}

func (q *Queries) UpsertLoginNonce(ctx context.Context, arg UpsertLoginNonceParams) error {
	_, err := q.db.ExecContext(ctx, upsertLoginNonce,
		arg.Address,
		arg.Nonce,
		arg.ExpiresAt,
		arg.Message,
	)
	return err
}
