// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Identity struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// 'google' | 'wallet'
	Provider string `json:"provider"`
	// google: sub; wallet: 0x... lowercased
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type LedgerEvent struct {
	ID int64 `json:"id"`
	// 'youtube'
	Platform string `json:"platform"`
	// channelId
	PlatformUserID string `json:"platform_user_id"`
	// nullable until claimed
	UserID sql.NullInt64 `json:"user_id"`
	// 'DIRECT' | 'ESCROW' | 'WITHDRAW'
	EventType string `json:"event_type"`
	// Token base units (MNEE decimals)
	AmountRaw string `json:"amount_raw"`
	// Optional tipper message, shown to creator
	Message   sql.NullString `json:"message"`
	TxHash    string         `json:"tx_hash"`
	LogIndex  int32          `json:"log_index"`
	BlockTime time.Time      `json:"block_time"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Payout struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// 'ethereum'
	Chain string `json:"chain"`
	// 0x...
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SocialLink struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// 'youtube'
	Platform string `json:"platform"`
	// YouTube channelId
	PlatformUserID string       `json:"platform_user_id"`
	VerifiedAt     sql.NullTime `json:"verified_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
