// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payouts.sql

package db

import (
	"context"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
  user_id, chain, address, created_at, updated_at
) VALUES (
  $1, $2, $3, NOW(), NOW()
)
RETURNING id, user_id, chain, address, created_at, updated_at
`

type CreatePayoutParams struct {
	UserID  int64  `json:"user_id"`
	Chain   string `json:"chain"`
	Address string `json:"address"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, createPayout, arg.UserID, arg.Chain, arg.Address)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Chain,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayout = `-- name: DeletePayout :exec
DELETE FROM payouts WHERE id = $1
`

func (q *Queries) DeletePayout(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePayout, id)
	return err
}

const getPayoutByUserAndChain = `-- name: GetPayoutByUserAndChain :one
SELECT id, user_id, chain, address, created_at, updated_at FROM payouts
WHERE user_id = $1 AND chain = $2
LIMIT 1
`

type GetPayoutByUserAndChainParams struct {
	UserID int64  `json:"user_id"`
	Chain  string `json:"chain"`
}

func (q *Queries) GetPayoutByUserAndChain(ctx context.Context, arg GetPayoutByUserAndChainParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, getPayoutByUserAndChain, arg.UserID, arg.Chain)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Chain,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayoutsByUser = `-- name: ListPayoutsByUser :many
SELECT id, user_id, chain, address, created_at, updated_at FROM payouts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPayoutsByUser(ctx context.Context, userID int64) ([]Payout, error) {
	rows, err := q.db.QueryContext(ctx, listPayoutsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Chain,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayoutAddress = `-- name: UpdatePayoutAddress :one
UPDATE payouts
SET address = $2, updated_at = NOW()
WHERE user_id = $1 AND chain = 'ethereum'
RETURNING id, user_id, chain, address, created_at, updated_at
`

type UpdatePayoutAddressParams struct {
	UserID  int64  `json:"user_id"`
	Address string `json:"address"`
}

func (q *Queries) UpdatePayoutAddress(ctx context.Context, arg UpdatePayoutAddressParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, updatePayoutAddress, arg.UserID, arg.Address)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Chain,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
