// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_links.sql

package db

import (
	"context"
	"database/sql"
)

const createSocialLink = `-- name: CreateSocialLink :one
INSERT INTO social_links (
  user_id, platform, platform_user_id, verified_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, NOW(), NOW()
)
RETURNING id, user_id, platform, platform_user_id, verified_at, created_at, updated_at
`

type CreateSocialLinkParams struct {
	UserID         int64        `json:"user_id"`
	Platform       string       `json:"platform"`
	PlatformUserID string       `json:"platform_user_id"`
	VerifiedAt     sql.NullTime `json:"verified_at"`
}

func (q *Queries) CreateSocialLink(ctx context.Context, arg CreateSocialLinkParams) (SocialLink, error) {
	row := q.db.QueryRowContext(ctx, createSocialLink,
		arg.UserID,
		arg.Platform,
		arg.PlatformUserID,
		arg.VerifiedAt,
	)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialLinkByPlatformUser = `-- name: GetSocialLinkByPlatformUser :one
SELECT id, user_id, platform, platform_user_id, verified_at, created_at, updated_at
FROM social_links
WHERE platform = $1 AND platform_user_id = $2
LIMIT 1
`

type GetSocialLinkByPlatformUserParams struct {
	Platform       string `json:"platform"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetSocialLinkByPlatformUser(ctx context.Context, arg GetSocialLinkByPlatformUserParams) (SocialLink, error) {
	row := q.db.QueryRowContext(ctx, getSocialLinkByPlatformUser, arg.Platform, arg.PlatformUserID)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
